import express from 'express'
import cookieParser from 'cookie-parser'
import helmet from 'helmet'
import cors from 'cors'
import rateLimit from 'express-rate-limit'
import path from 'node:path'
import { config } from './config.js'
import { errors } from './http.js'
import { authRouter } from './auth.js'
import { adminRouter } from './routes.js'
import { publicRouter } from './public.js'
export const app=express(); app.set('trust proxy',1); app.use(helmet());app.use(cors({origin:config.origin,credentials:true}));app.use(express.json({limit:'1mb'}));app.use(cookieParser());app.get('/api/health',(_q,r)=>r.json({status:'ok'}));app.use('/api/v1/auth',rateLimit({windowMs:15*60_000,max:config.authRateLimitMax,standardHeaders:true,legacyHeaders:false}),authRouter);app.use('/api/v1/public',publicRouter);if(config.uploadProvider==='local')app.use('/api/v1/media',(req,res,next)=>req.method==='GET'||req.method==='HEAD'?express.static(path.resolve(config.uploadDir), { fallthrough:false, index:false })(req,res,next):next());app.use('/api/v1',adminRouter);app.use(errors)
