import { Router } from 'express'
import { z } from 'zod'
import { prisma } from './db.js'
import { allow, requireAuth } from './auth.js'
import { HttpError, asyncRoute, pagination } from './http.js'
import { moveInventory } from './inventory.js'
import crypto from 'node:crypto'
import multer from 'multer'
import fs from 'node:fs/promises'
import path from 'node:path'
import { config } from './config.js'

const status=z.enum(['ACTIVE','INACTIVE','DRAFT','ARCHIVED','DISABLED','EXPIRED'])
const list=(model:any, searchField?:string)=>asyncRoute(async(req,res)=>{const {page,limit,skip}=pagination(req), q=String(req.query.q??'');const where:any={businessId:req.principal!.businessId,...(q&&searchField?{[searchField]:{contains:q,mode:'insensitive'}}:{})};const [items,total]=await prisma.$transaction([model.findMany({where,skip,take:limit,orderBy:{createdAt:'desc'}}),model.count({where})]);res.json({data:items,meta:{page,limit,total}})})
export const adminRouter=Router(); adminRouter.use(requireAuth)
adminRouter.get('/categories',list(prisma.category,'name')); adminRouter.post('/categories',allow('OWNER','ADMIN'),asyncRoute(async(req,res)=>{const d=z.object({name:z.string().min(2),slug:z.string().regex(/^[a-z0-9-]+$/),status:status.optional()}).parse(req.body);res.status(201).json({data:await prisma.category.create({data:{...d,businessId:req.principal!.businessId}})})}))
adminRouter.get('/attributes',asyncRoute(async(req,res)=>res.json({data:await prisma.attribute.findMany({where:{businessId:req.principal!.businessId},include:{values:true}})}))); adminRouter.post('/attributes',allow('OWNER','ADMIN'),asyncRoute(async(req,res)=>{const d=z.object({name:z.string(),kind:z.enum(['COLOR','TEXT','SIZE','SELECT']),values:z.array(z.object({value:z.string(),hex:z.string().optional()})).default([])}).parse(req.body);res.status(201).json({data:await prisma.attribute.create({data:{businessId:req.principal!.businessId,name:d.name,kind:d.kind,values:{create:d.values}} ,include:{values:true}})})}))
adminRouter.get('/customers',list(prisma.customer,'businessName')); adminRouter.post('/customers',allow('OWNER','ADMIN','STAFF','SALES'),asyncRoute(async(req,res)=>{const d=z.object({businessName:z.string(),contactPerson:z.string(),phone:z.string(),whatsapp:z.string().optional(),email:z.string().email().optional(),city:z.string().optional(),state:z.string().optional(),type:z.enum(['WHOLESALER','RETAILER','DISTRIBUTOR','RESELLER']),gstNumber:z.string().optional(),notes:z.string().optional(),status:status.optional()}).parse(req.body);res.status(201).json({data:await prisma.customer.create({data:{...d,businessId:req.principal!.businessId}})})}))
adminRouter.get('/customers/:id',asyncRoute(async(req,res)=>{const x=await prisma.customer.findFirst({where:{id:String(req.params.id),businessId:req.principal!.businessId}});if(!x)throw new HttpError(404,'Customer not found','NOT_FOUND');res.json({data:x})})); adminRouter.patch('/customers/:id',allow('OWNER','ADMIN','STAFF','SALES'),asyncRoute(async(req,res)=>{const d=z.object({businessName:z.string().optional(),contactPerson:z.string().optional(),phone:z.string().optional(),status:status.optional(),notes:z.string().optional()}).parse(req.body);const x=await prisma.customer.updateMany({where:{id:String(req.params.id),businessId:req.principal!.businessId},data:d});if(!x.count)throw new HttpError(404,'Customer not found','NOT_FOUND');res.status(204).end()}))
const productInput=z.object({categoryId:z.string(),code:z.string().min(1),name:z.string().min(1),description:z.string().default(''),basePrice:z.number().nonnegative(),moq:z.number().int().positive().default(1),status:status.optional(),attributeIds:z.array(z.string()).default([]),media:z.array(z.object({objectKey:z.string(),url:z.string(),mimeType:z.string(),primary:z.boolean().optional(),sortOrder:z.number().int().optional()})).default([]),variants:z.array(z.object({sku:z.string().min(1),price:z.number().nonnegative(),stock:z.number().int().nonnegative().default(0),attributeValueIds:z.array(z.string()).default([])})).min(1)})
adminRouter.get('/products',asyncRoute(async(req,res)=>{const {page,limit,skip}=pagination(req),q=String(req.query.q??'');const where={businessId:req.principal!.businessId,...(q?{OR:[{name:{contains:q,mode:'insensitive' as const}},{code:{contains:q,mode:'insensitive' as const}}]}:{})};const [data,total]=await prisma.$transaction([prisma.product.findMany({where,skip,take:limit,include:{category:true,media:true,variants:{include:{attributeValues:{include:{attributeValue:{include:{attribute:true}}}}}}},orderBy:{createdAt:'desc'}}),prisma.product.count({where})]);res.json({data,meta:{page,limit,total}})}))
adminRouter.post('/products',allow('OWNER','ADMIN','STAFF'),asyncRoute(async(req,res)=>{const d=productInput.parse(req.body);const category=await prisma.category.findFirst({where:{id:d.categoryId,businessId:req.principal!.businessId}});if(!category)throw new HttpError(400,'Invalid category','VALIDATION_ERROR');const product=await prisma.product.create({data:{businessId:req.principal!.businessId,categoryId:d.categoryId,code:d.code,name:d.name,description:d.description,basePrice:d.basePrice,moq:d.moq,status:d.status,media:{create:d.media},attributes:{create:d.attributeIds.map(attributeId=>({attributeId}))},variants:{create:d.variants.map(v=>({sku:v.sku,price:v.price,stock:v.stock,attributeValues:{create:v.attributeValueIds.map(attributeValueId=>({attributeValueId}))}}))}},include:{media:true,variants:{include:{attributeValues:true}}}});res.status(201).json({data:product})}))
adminRouter.get('/products/:id',asyncRoute(async(req,res)=>{const x=await prisma.product.findFirst({where:{id:String(req.params.id),businessId:req.principal!.businessId},include:{category:true,media:true,attributes:{include:{attribute:true}},variants:{include:{attributeValues:{include:{attributeValue:{include:{attribute:true}}}}}}}});if(!x)throw new HttpError(404,'Product not found','NOT_FOUND');res.json({data:x})})); adminRouter.patch('/products/:id',allow('OWNER','ADMIN','STAFF'),asyncRoute(async(req,res)=>{const d=productInput.partial().omit({variants:true,attributeIds:true}).parse(req.body);const x=await prisma.product.updateMany({where:{id:String(req.params.id),businessId:req.principal!.businessId},data:d});if(!x.count)throw new HttpError(404,'Product not found','NOT_FOUND');await prisma.auditLog.create({data:{businessId:req.principal!.businessId,actorId:req.principal!.id,action:'PRODUCT_UPDATED',entity:'Product',entityId:String(req.params.id)}});res.status(204).end()}))
adminRouter.post('/inventory/movements',allow('OWNER','ADMIN','STAFF','INVENTORY_MANAGER'),asyncRoute(async(req,res)=>{const d=z.object({variantId:z.string(),type:z.enum(['PRODUCTION','SALE','ADJUSTMENT','DAMAGE','RETURN','RESERVATION','RELEASE']),quantity:z.number().int().positive(),reason:z.string().min(2),reference:z.string().optional()}).parse(req.body);res.status(201).json({data:await moveInventory(req.principal!,d)})}))
const allowedMime=new Set(['image/jpeg','image/png','image/webp','image/gif'])
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:config.uploadMaxBytes,files:1},fileFilter:(_req,file,cb)=>cb(null,allowedMime.has(file.mimetype))})
adminRouter.post('/media',allow('OWNER','ADMIN','STAFF'),upload.single('file'),asyncRoute(async(req,res)=>{if(config.uploadProvider!=='local')throw new HttpError(501,'Configured upload provider is not available','UPLOAD_UNAVAILABLE');if(!req.file)throw new HttpError(400,'A supported image file is required','VALIDATION_ERROR');const ext=({ 'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','image/gif':'.gif'} as Record<string,string>)[req.file.mimetype];const objectKey=`${req.principal!.businessId}/${crypto.randomUUID()}${ext}`;const destination=path.resolve(config.uploadDir,objectKey);await fs.mkdir(path.dirname(destination),{recursive:true});await fs.writeFile(destination,req.file.buffer,{flag:'wx'});res.status(201).json({data:{objectKey,url:`/api/v1/media/${objectKey}`,mimeType:req.file.mimetype}})}))
adminRouter.get('/collections',asyncRoute(async(req,res)=>{const {page,limit,skip}=pagination(req),q=String(req.query.q??'');const where:any={businessId:req.principal!.businessId,...(q?{name:{contains:q,mode:'insensitive'}}:{})};const [data,total]=await prisma.$transaction([prisma.collection.findMany({where,skip,take:limit,include:{products:true},orderBy:{createdAt:'desc'}}),prisma.collection.count({where})]);res.json({data,meta:{page,limit,total}})})); adminRouter.post('/collections',allow('OWNER','ADMIN','STAFF'),asyncRoute(async(req,res)=>{const d=z.object({name:z.string(),description:z.string().default(''),productIds:z.array(z.string()).default([]),status:status.optional()}).parse(req.body);res.status(201).json({data:await prisma.collection.create({data:{businessId:req.principal!.businessId,name:d.name,description:d.description,status:d.status,products:{create:d.productIds.map(productId=>({productId}))}},include:{products:true}})})}))
adminRouter.patch('/collections/:id',allow('OWNER','ADMIN','STAFF'),asyncRoute(async(req,res)=>{const d=z.object({name:z.string().optional(),description:z.string().optional(),status:status.optional()}).parse(req.body);const x=await prisma.collection.updateMany({where:{id:String(req.params.id),businessId:req.principal!.businessId},data:d});if(!x.count)throw new HttpError(404,'Collection not found','NOT_FOUND');res.status(204).end()}))
const catalogueInput=z.object({customerId:z.string().optional(),title:z.string(),message:z.string().optional(),expiresAt:z.coerce.date().optional(),status:status.optional(),showPrice:z.boolean().default(true),showExactStock:z.boolean().default(false),showAvailability:z.boolean().default(true),showMOQ:z.boolean().default(true),allowSelection:z.boolean().default(true),allowEnquiry:z.boolean().default(true),allowImageDownload:z.boolean().default(false),priceAdjustmentPct:z.number().min(-100).max(100).default(0),pin:z.string().min(4).optional(),items:z.array(z.object({productId:z.string(),variantId:z.string().optional(),customPrice:z.number().nonnegative().optional()})).min(1)})
adminRouter.get('/catalogues',asyncRoute(async(req,res)=>{const {page,limit,skip}=pagination(req),q=String(req.query.q??'');const where:any={businessId:req.principal!.businessId,...(q?{title:{contains:q,mode:'insensitive'}}:{})};const [data,total]=await prisma.$transaction([prisma.catalogue.findMany({where,skip,take:limit,include:{items:true},orderBy:{createdAt:'desc'}}),prisma.catalogue.count({where})]);res.json({data,meta:{page,limit,total}})})); adminRouter.post('/catalogues',allow('OWNER','ADMIN','STAFF','SALES'),asyncRoute(async(req,res)=>{const d=catalogueInput.parse(req.body);const token=crypto.randomBytes(24).toString('base64url');const pinHash=d.pin?await (await import('argon2')).default.hash(d.pin):undefined;const catalogue=await prisma.catalogue.create({data:{...d,pin:undefined,pinHash,businessId:req.principal!.businessId,token,items:{create:d.items}},include:{items:true}});await prisma.auditLog.create({data:{businessId:req.principal!.businessId,actorId:req.principal!.id,action:'CATALOGUE_CREATED',entity:'Catalogue',entityId:catalogue.id}});res.status(201).json({data:catalogue})}))
adminRouter.post('/catalogues/:id/disable',allow('OWNER','ADMIN'),asyncRoute(async(req,res)=>{const r=await prisma.catalogue.updateMany({where:{id:String(req.params.id),businessId:req.principal!.businessId},data:{status:'DISABLED'}});if(!r.count)throw new HttpError(404,'Catalogue not found','NOT_FOUND');await prisma.auditLog.create({data:{businessId:req.principal!.businessId,actorId:req.principal!.id,action:'CATALOGUE_DISABLED',entity:'Catalogue',entityId:String(req.params.id)}});res.status(204).end()}))
adminRouter.patch('/catalogues/:id',allow('OWNER','ADMIN','STAFF','SALES'),asyncRoute(async(req,res)=>{const d=catalogueInput.partial().parse(req.body);const x=await prisma.catalogue.updateMany({where:{id:String(req.params.id),businessId:req.principal!.businessId},data:{...d,items:undefined,pin:undefined}});if(!x.count)throw new HttpError(404,'Catalogue not found','NOT_FOUND');res.status(204).end()})); adminRouter.delete('/catalogues/:id',allow('OWNER','ADMIN'),asyncRoute(async(req,res)=>{const x=await prisma.catalogue.deleteMany({where:{id:String(req.params.id),businessId:req.principal!.businessId}});if(!x.count)throw new HttpError(404,'Catalogue not found','NOT_FOUND');res.status(204).end()}))
adminRouter.get('/enquiries',asyncRoute(async(req,res)=>{const {page,limit,skip}=pagination(req);const where={businessId:req.principal!.businessId,...(req.query.status?{status:String(req.query.status) as any}:{})};const [data,total]=await prisma.$transaction([prisma.enquiry.findMany({where,skip,take:limit,include:{items:true,customer:true},orderBy:{createdAt:'desc'}}),prisma.enquiry.count({where})]);res.json({data,meta:{page,limit,total}})})); adminRouter.patch('/enquiries/:id/status',allow('OWNER','ADMIN','STAFF','SALES'),asyncRoute(async(req,res)=>{const d=z.object({status:z.enum(['NEW','CONTACTED','NEGOTIATING','CONVERTED','CLOSED']),note:z.string().optional()}).parse(req.body);const x=await prisma.enquiry.updateMany({where:{id:String(req.params.id),businessId:req.principal!.businessId},data:{status:d.status}});if(!x.count)throw new HttpError(404,'Enquiry not found','NOT_FOUND');await prisma.enquiryStatusHistory.create({data:{enquiryId:String(req.params.id),...d}});res.status(204).end()}))

